# C:\Users\franc\OneDrive\Desktop\financialAdvisorv2\docker-compose.yml
# Sin línea 'version'

services:
  # --- Servicio de la Base de Datos Vectorial (ChromaDB) ---
  vector_db:
    image: chromadb/chroma
    ports:
      - "8001:8000" # Mapea el puerto 8001 del HOST a 8000 del CONTENEDOR
    volumes:
      - chromadb_data:/chroma/data # Almacenamiento persistente
    restart: always # Que intente reiniciarse si se cae


  # --- Servicio del Backend (FastAPI) ---
  backend:
    build: ./backend # Ruta a tu carpeta 'backend'
    ports:
      - "8000:8000"
    # Sin 'env_file' (puedes descomentarlo si lo necesitas y el archivo existe)
    depends_on:
      - vector_db # Solo asegura el orden de inicio, no espera a que esté saludable
    environment:
      CHROMADB_HOST: vector_db
      CHROMADB_PORT: 8000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./backend:/app # Mapea el código local
    restart: always # Que intente reiniciarse si se cae
    env_file: .env


  # --- Servicio del Frontend (React) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # O el puerto que uses para tu frontend (ej. "3000:3000")
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # --- ¡¡¡CAMBIO CRÍTICO AQUÍ!!! ---
      # Le decimos al frontend que el backend es localhost:8000
      REACT_APP_API_URL: http://localhost:8000
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    command: ["npm", "start"]
    restart: always


# --- Volúmenes para persistencia de datos ---
volumes:
  chromadb_data: