# PROVISIONAL. EN REALIDAD VAMOS A CONECTARNOS DE STREAMLIT A LA API DE FASTAPI, NO A OPENAI DIRECTAMENTE. ES SOLO PARA QUE CHEQUEEN AHORA QUE FUNCIONA STREAMLIT CON EL CODIGO QUE TENGO. 

OPENAI_API_KEY = "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"
